import streamlit as st
import xml.etree.ElementTree as ET
from xml.dom import minidom
import pandas as pd
import json
import re
import os
from urllib.parse import urlparse

st.set_page_config(page_title="Enterprise JMeter JMX Studio", layout="wide")


# ==========================================
# PARSER ENGINE: HAR, EXCEL, SWAGGER
# ==========================================

def parse_har_file(har_data, user_cookie="", scenario_prefix="", deduct_duplicates=True, exclude_static=True):
    parsed_apis = []
    seen_endpoints = set()
    entries = har_data.get("log", {}).get("entries", [])

    for entry in entries:
        request = entry.get("request", {})
        url = request.get("url", "")
        method = request.get("method", "GET").upper()
        parsed_url = urlparse(url)
        domain = parsed_url.netloc
        path = parsed_url.path

        if parsed_url.query:
            path += f"?{parsed_url.query}"

        # Deduplication
        endpoint_key = f"{method}:{parsed_url.path.rstrip('/')}"
        if deduct_duplicates:
            if endpoint_key in seen_endpoints:
                continue
            seen_endpoints.add(endpoint_key)

        # Exclude static noise
        if exclude_static and any(parsed_url.path.lower().endswith(ext) for ext in
                                  [".css", ".js", ".png", ".jpg", ".jpeg", ".svg", ".ico", ".woff", ".woff2", ".ttf"]):
            continue

        headers = {}
        for h in request.get("headers", []):
            name, value = h.get("name", ""), h.get("value", "")
            if not name.startswith(":") and name.lower() not in ["content-length", "host"]:
                headers[name] = value

        if user_cookie.strip():
            headers["Cookie"] = user_cookie.strip()

        body = request.get("postData", {}).get("text")

        # Clean Scenario & Endpoint Naming
        path_segments = [seg for seg in parsed_url.path.strip("/").split("/") if seg]
        if path_segments:
            last_segment = path_segments[-1]
            if re.match(r'^[a-f0-9\-]{8,}$', last_segment) and len(path_segments) > 1:
                endpoint_label = f"{path_segments[-2]}_{last_segment[:8]}"
            else:
                endpoint_label = last_segment.replace("-", "_")
        else:
            endpoint_label = "root"

        prefix = f"{scenario_prefix.strip()}_" if scenario_prefix.strip() else ""
        sampler_name = f"{prefix}{method}_{endpoint_label}"

        parsed_apis.append({
            "name": sampler_name,
            "method": method,
            "base_url": domain,
            "path": path,
            "headers": headers,
            "body": body
        })

    return parsed_apis


def inject_jmeter_functions(text_val):
    if not isinstance(text_val, str):
        return text_val
    text_val = re.sub(r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+Z?', r"${__time(yyyy-MM-dd'T'HH:mm:ss.SSS'Z')}",
                      text_val)
    text_val = re.sub(r'\d{4}-\d{2}-\d{2}', r'${__time(yyyy-MM-dd)}', text_val)
    text_val = re.sub(r'[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}', r'${__UUID()}', text_val)
    text_val = re.sub(r'\b\d{5,10}\b', r'${__Random(10000,999999)}', text_val)
    return text_val


# ==========================================
# JMX XML ENGINE WITH DYNAMIC DOMAIN HMAC & CORRELATION
# ==========================================

def create_standard_jmx(api_list, test_plan_name="Enterprise Test Plan", jar_paths=None):
    test_plan = ET.Element("jmeterTestPlan", version="1.2", properties="5.0", jmeter="5.5")
    hash_tree = ET.SubElement(test_plan, "hashTree")

    tp = ET.SubElement(hash_tree, "TestPlan", guiclass="TestPlanGui", testclass="TestPlan", testname=test_plan_name,
                       enabled="true")
    ET.SubElement(tp, "stringProp", name="TestPlan.comments").text = "Generated by Enterprise JMX Generator Engine"
    ET.SubElement(tp, "boolProp", name="TestPlan.functional_mode").text = "false"
    ET.SubElement(tp, "boolProp", name="TestPlan.serialize_threadgroups").text = "false"
    ET.SubElement(tp, "stringProp", name="TestPlan.user_define_classpath").text = (
        ";".join(jar_paths) if os.name == 'nt' else ":".join(jar_paths)) if jar_paths else ""

    tp_hash = ET.SubElement(hash_tree, "hashTree")

    # Detect primary domain from first API entry
    primary_domain = api_list[0].get("base_url", "orderv2.foodtruck-qa.com") if api_list else "orderv2.foodtruck-qa.com"

    # User Defined Variables (UDV)
    udv = ET.SubElement(tp_hash, "Arguments", guiclass="ArgumentsPanel", testclass="Arguments",
                        testname="User Defined Variables", enabled="true")
    udv_coll = ET.SubElement(udv, "collectionProp", name="Arguments.arguments")
    for v in [{"name": "BASE_URL", "value": primary_domain}, {"name": "PORT", "value": "443"},
              {"name": "PROTOCOL", "value": "https"}]:
        arg_elem = ET.SubElement(udv_coll, "elementProp", name=v["name"], elementType="Argument")
        ET.SubElement(arg_elem, "stringProp", name="Argument.name").text = v["name"]
        ET.SubElement(arg_elem, "stringProp", name="Argument.value").text = v["value"]
        ET.SubElement(arg_elem, "stringProp", name="Argument.metadata").text = "="

    ET.SubElement(tp_hash, "hashTree")

    # View Results Tree Listener
    vrt = ET.SubElement(tp_hash, "ResultCollector", guiclass="ViewResultsFullVisualizer", testclass="ResultCollector",
                        testname="View Results Tree", enabled="true")
    ET.SubElement(vrt, "boolProp", name="ResultCollector.error_logging").text = "false"
    obj_quant = ET.SubElement(vrt, "objProp")
    ET.SubElement(obj_quant, "name").text = "saveConfig"
    value_elem = ET.SubElement(obj_quant, "value", attrib={"class": "SampleSaveConfiguration"})
    for prop in ["time", "latency", "timestamp", "success", "label", "code", "message", "threadName", "dataType",
                 "bytes", "sentBytes", "url", "connectTime"]:
        ET.SubElement(value_elem, prop).text = "true"

    ET.SubElement(tp_hash, "hashTree")

    # Thread Group
    tg = ET.SubElement(tp_hash, "ThreadGroup", guiclass="ThreadGroupGui", testclass="ThreadGroup",
                       testname="Thread Group - Scenarios", enabled="true")
    ET.SubElement(tg, "stringProp", name="ThreadGroup.on_sample_error").text = "continue"
    lc = ET.SubElement(tg, "elementProp", name="ThreadGroup.main_controller", elementType="LoopController",
                       guiclass="LoopControlPanel", testclass="LoopController", testname="Loop Controller",
                       enabled="true")
    ET.SubElement(lc, "boolProp", name="LoopController.continue_forever").text = "false"
    ET.SubElement(lc, "stringProp", name="LoopController.loops").text = "1"
    ET.SubElement(tg, "stringProp", name="ThreadGroup.num_threads").text = "1"
    ET.SubElement(tg, "stringProp", name="ThreadGroup.ramp_time").text = "1"

    tg_hash = ET.SubElement(tp_hash, "hashTree")

    # Global Cookie Manager
    cookie_mgr = ET.SubElement(tg_hash, "CookieManager", guiclass="CookiePanel", testclass="CookieManager",
                               testname="HTTP Cookie Manager", enabled="true")
    ET.SubElement(cookie_mgr, "boolProp", name="CookieManager.clearEachIteration").text = "false"
    ET.SubElement(cookie_mgr, "stringProp", name="CookieManager.policy").text = "standard"
    ET.SubElement(tg_hash, "hashTree")

    # Global JSR223 Dynamic HMAC PreProcessor
    jsr223 = ET.SubElement(tg_hash, "JSR223PreProcessor", guiclass="TestBeanGUI", testclass="JSR223PreProcessor",
                           testname="JSR223 Dynamic HMAC PreProcessor", enabled="true")
    ET.SubElement(jsr223, "stringProp", name="scriptLanguage").text = "groovy"
    ET.SubElement(jsr223, "stringProp", name="parameters").text = ""
    ET.SubElement(jsr223, "stringProp", name="filename").text = ""
    ET.SubElement(jsr223, "stringProp", name="cacheKey").text = "true"

    groovy_script = """import javax.crypto.Mac
import javax.crypto.spec.SecretKeySpec
import java.util.Base64
import groovy.json.JsonSlurper
import groovy.json.JsonOutput
import java.net.URL
import java.net.HttpURLConnection

// 1. Precise Time Sync with Fallback Clock Offset (-148s)
long serverAdjustedMs = System.currentTimeMillis()
try {
    String currentDomain = sampler.getDomain()
    if (currentDomain == null || currentDomain.isEmpty() || currentDomain.startsWith("\${")) {
        currentDomain = vars.get("BASE_URL")
    }
    URL url = new URL("https://" + currentDomain + "/")
    HttpURLConnection conn = (HttpURLConnection) url.openConnection()
    conn.setRequestMethod("HEAD")
    conn.setConnectTimeout(1500)
    conn.setReadTimeout(1500)
    long serverTime = conn.getHeaderFieldDate("Date", 0)
    if (serverTime > 0) {
        serverAdjustedMs = serverTime
    }
    conn.disconnect()
} catch (Exception e) {
    serverAdjustedMs = System.currentTimeMillis() - 148000L
}

String timestamp = String.valueOf(serverAdjustedMs)

// 2. Base64 Secret Key Setup
String secretKeyBase64 = "YWFiODUzMjYtYzhiYS00NjBhLWEyY2EtNmY4MDczNTUwZjlhCg==".trim()
byte[] keyBytes = Base64.getDecoder().decode(secretKeyBase64)
if (keyBytes.length > 0 && keyBytes[keyBytes.length - 1] == (byte) 10) {
    keyBytes = keyBytes[0..<keyBytes.length - 1] as byte[]
}

// 3. Dynamic HTTP Domain and Method Extraction
String method = sampler.getMethod().toLowerCase()
String domain = sampler.getDomain()
if (domain == null || domain.isEmpty() || domain.startsWith("\${")) {
    domain = vars.get("BASE_URL")
}

// 4. Safe Path & Query String Extraction
String fullPath = sampler.getPath().trim()
String pathOnly = fullPath
String rawQuery = ""

int qIndex = fullPath.indexOf("?")
if (qIndex != -1) {
    pathOnly = fullPath.substring(0, qIndex)
    rawQuery = fullPath.substring(qIndex + 1)
} else if (sampler.getQueryString() != null && !sampler.getQueryString().trim().isEmpty()) {
    rawQuery = sampler.getQueryString().trim()
}

// 5. Query String Parameter Sorting
String sortedQueryString = ""
if (!rawQuery.isEmpty()) {
    if (rawQuery.startsWith("?")) {
        rawQuery = rawQuery.substring(1)
    }
    Map<String, String> paramMap = [:]
    rawQuery.split("&").each { param ->
        int eqIndex = param.indexOf("=")
        if (eqIndex != -1) {
            paramMap.put(param.substring(0, eqIndex), param.substring(eqIndex + 1))
        } else {
            paramMap.put(param, "")
        }
    }
    sortedQueryString = paramMap.sort { a, b -> a.key <=> b.key }
                                .collect { k, v -> "${k}=${v}" }
                                .join("&")
}

// 6. Build String to Sign (Matches Frontend JS Construction)
StringBuilder sb = new StringBuilder()
sb.append(method).append("\\n")
  .append(domain).append("\\n")
  .append(pathOnly).append("\\n")
  .append(timestamp)

if (!sortedQueryString.isEmpty()) {
    sb.append("\\n").append(sortedQueryString)
}

// 7. Request Body Minification
String body = sampler.getArguments().getArgument(0)?.getValue()
if (body != null && !body.trim().isEmpty()) {
    try {
        def parsedJson = new JsonSlurper().parseText(body)
        String minifiedJson = JsonOutput.toJson(parsedJson)
        sb.append("\\n").append(minifiedJson)
    } catch (Exception e) {
        sb.append("\\n").append(body.trim())
    }
}

String stringToSign = sb.toString()

// 8. Compute HMAC SHA-256 Signature
Mac mac = Mac.getInstance("HmacSHA256")
SecretKeySpec keySpec = new SecretKeySpec(keyBytes, "HmacSHA256")
mac.init(keySpec)

byte[] hmacData = mac.doFinal(stringToSign.getBytes("UTF-8"))
String hmacHeader = Base64.getEncoder().encodeToString(hmacData)

// 9. Store Variables for Header Manager
vars.put("dynamicTimestamp", timestamp)
vars.put("dynamicHmac", hmacHeader)"""

    ET.SubElement(jsr223, "stringProp", name="script").text = groovy_script
    ET.SubElement(tg_hash, "hashTree")

    # Generate Samplers
    for idx, api in enumerate(api_list):
        sampler_name = api.get("name") or f"Sampler_{idx + 1}"
        method = api.get("method", "GET").upper()
        path = str(api.get("path") or "/").strip()
        headers = api.get("headers") or {}
        body = api.get("body")
        domain_override = api.get("base_url") or "${BASE_URL}"

        if path and not path.startswith("/"):
            path = "/" + path

        http = ET.SubElement(tg_hash, "HTTPSamplerProxy", guiclass="HttpTestSampleGui", testclass="HTTPSamplerProxy",
                             testname=sampler_name, enabled="true")

        # Domain configuration
        if domain_override and domain_override != primary_domain:
            ET.SubElement(http, "stringProp", name="HTTPSampler.domain").text = domain_override
        else:
            ET.SubElement(http, "stringProp", name="HTTPSampler.domain").text = "${BASE_URL}"

        ET.SubElement(http, "stringProp", name="HTTPSampler.port").text = "${PORT}"
        ET.SubElement(http, "stringProp", name="HTTPSampler.protocol").text = "${PROTOCOL}"
        ET.SubElement(http, "stringProp", name="HTTPSampler.path").text = path
        ET.SubElement(http, "stringProp", name="HTTPSampler.method").text = method
        ET.SubElement(http, "boolProp", name="HTTPSampler.follow_redirects").text = "false"
        ET.SubElement(http, "boolProp", name="HTTPSampler.auto_redirects").text = "false"
        ET.SubElement(http, "boolProp", name="HTTPSampler.use_keepalive").text = "true"

        if body and str(body).strip() and str(body).lower() != "nan":
            body_with_functions = inject_jmeter_functions(str(body))
            ET.SubElement(http, "boolProp", name="HTTPSampler.postBodyRaw").text = "true"
            body_args = ET.SubElement(http, "elementProp", name="HTTPsampler.Arguments", elementType="Arguments")
            coll = ET.SubElement(body_args, "collectionProp", name="Arguments.arguments")
            arg = ET.SubElement(coll, "elementProp", name="", elementType="HTTPArgument")
            ET.SubElement(arg, "boolProp", name="HTTPArgument.always_encode").text = "false"
            ET.SubElement(arg, "stringProp", name="Argument.value").text = body_with_functions

        sampler_hash = ET.SubElement(tg_hash, "hashTree")

        # Header Manager Construction
        hm = ET.SubElement(sampler_hash, "HeaderManager", guiclass="HeaderPanel", testclass="HeaderManager",
                           testname="HTTP Header Manager", enabled="true")
        h_coll = ET.SubElement(hm, "collectionProp", name="HeaderManager.headers")

        # Selective Header Dynamic Injection
        has_hmac_in_har = any(k.lower() == "x-hmac" for k in headers.keys())
        has_timestamp_in_har = any(k.lower() == "x-timestamp" for k in headers.keys())

        header_map = {}
        for h_k, h_v in headers.items():
            if h_k.startswith(":") or h_k.lower() in ["content-length", "host"]:
                continue
            header_map[h_k] = str(h_v)

        if has_hmac_in_har or "order/ajax" in path.lower():
            header_map["x-hmac"] = "${dynamicHmac}"
            header_map["x-timestamp"] = "${dynamicTimestamp}"
            header_map["x-request-id"] = "${__UUID()}"
        elif has_timestamp_in_har:
            header_map["x-timestamp"] = "${dynamicTimestamp}"

        for h_k, h_v in header_map.items():
            h_elem = ET.SubElement(h_coll, "elementProp", name="", elementType="Header")
            ET.SubElement(h_elem, "stringProp", name="Header.name").text = str(h_k)
            ET.SubElement(h_elem, "stringProp", name="Header.value").text = str(h_v)

        ET.SubElement(sampler_hash, "hashTree")

        # Think Time Execution Placement
        timer = ET.SubElement(sampler_hash, "GaussianRandomTimer", guiclass="GaussianRandomTimerGui",
                              testclass="GaussianRandomTimer", testname="Think Time", enabled="true")
        ET.SubElement(timer, "stringProp", name="ConstantTimer.delay").text = "1000"
        ET.SubElement(timer, "stringProp", name="GaussianRandomTimer.deviation").text = "500"
        ET.SubElement(sampler_hash, "hashTree")

        # Correlation Extractor for Session & Identity tokens
        if any(term in path.lower() for term in ["session", "active", "login", "identity"]):
            regex = ET.SubElement(sampler_hash, "RegexExtractor", guiclass="RegexExtractorGui",
                                  testclass="RegexExtractor", testname="Auto Extractor - SessionId", enabled="true")
            ET.SubElement(regex, "stringProp", name="RegexExtractor.useHeaders").text = "false"
            ET.SubElement(regex, "stringProp", name="RegexExtractor.refname").text = "SessionId"
            ET.SubElement(regex, "stringProp",
                          name="RegexExtractor.regex").text = r'"(?:user_id|SessionId|token)"\s*:\s*"([^"]+)"'
            ET.SubElement(regex, "stringProp", name="RegexExtractor.template").text = "$1$"
            ET.SubElement(regex, "stringProp", name="RegexExtractor.default").text = "NOT_FOUND"
            ET.SubElement(regex, "stringProp", name="RegexExtractor.match_number").text = "1"
            ET.SubElement(sampler_hash, "hashTree")

    xml_raw = ET.tostring(test_plan, encoding="utf-8")
    return minidom.parseString(xml_raw).toprettyxml(indent="  ")


# ==========================================
# STREAMLIT UI LAYOUT & SIDEBAR
# ==========================================

st.sidebar.header("📦 JMeter Classpath & JAR Options")
uploaded_jars = st.sidebar.file_uploader("Upload External JAR Files:", type=["jar"], accept_multiple_files=True,
                                         key="jar_uploader")

jar_file_paths = []
if uploaded_jars:
    os.makedirs("jmeter_jars", exist_ok=True)
    for jar in uploaded_jars:
        file_path = os.path.join("jmeter_jars", jar.name)
        with open(file_path, "wb") as f:
            f.write(jar.getbuffer())
        jar_file_paths.append(file_path)
    st.sidebar.success(f"Attached {len(jar_file_paths)} JAR file(s)!")

st.title("🚀 Enterprise JMeter JMX Generator Studio")

tab1, tab2, tab3, tab4 = st.tabs([
    "📄 1. JMX Generator (HAR/Excel/JSON/Swagger)",
    "🎯 2. API Recommendation Engine",
    "🎥 3. Clean Web Recorder",
    "🛠️ 4. JMX Script Editor & Tuner"
])

# ------------------------------------------
# TAB 1: SCRIPT GENERATOR
# ------------------------------------------
with tab1:
    st.header("Generate JMX from Direct Sources")
    source_type = st.radio("Select Input Source:", ["DevTools HAR File (.har)", "Excel File", "Swagger / OpenAPI JSON"])

    parsed_apis = []

    col_a, col_b = st.columns(2)
    with col_a:
        scenario_name = st.text_input("Scenario / Feature Prefix (e.g. KDS, RLP, DeliveryZone):",
                                      value="DeliveryZone_Scenario1")
        deduct_dupes = st.checkbox("Delete Duplicate Endpoints (Recommended)", value=True)
    with col_b:
        user_cookie = st.text_area("Paste Active Session Cookie String (from DevTools):",
                                   placeholder="OptanonAlertBoxClosed=...; _pxvid=...; CF_Authorization=...",
                                   height=100)

    if source_type == "DevTools HAR File (.har)":
        har_file = st.file_uploader("Upload DevTools HAR File", type=["har", "json"], key="tab1_har")
        if har_file:
            har_json = json.load(har_file)
            parsed_apis = parse_har_file(har_json, user_cookie=user_cookie, scenario_prefix=scenario_name,
                                         deduct_duplicates=deduct_dupes)
            st.success(f"Extracted {len(parsed_apis)} unique API requests from HAR file!")
            df_preview = pd.DataFrame(
                [{"Name": a["name"], "Method": a["method"], "Domain": a["base_url"], "Path": a["path"]} for a in
                 parsed_apis])
            st.dataframe(df_preview)

    elif source_type == "Excel File":
        uploaded_file = st.file_uploader("Upload Excel File", type=["xlsx", "xls"], key="tab1_excel")
        if uploaded_file:
            df = pd.read_excel(uploaded_file)
            st.write("Preview:", df.head(3))
            for idx, row in df.iterrows():
                name = row.get("Test_Case_Name") or row.get("Name") or f"API_{idx + 1}"
                method = row.get("httpMethod") or row.get("Method") or "GET"
                base_url = row.get("Source_BaseURL") or row.get("baseUrl") or row.get("Domain") or "${BASE_URL}"
                endpoint = row.get("endPoint") or row.get("Path") or "/"
                headers_raw = row.get("headers") or row.get("Headers")
                body = row.get("BodyFormat") or row.get("Body")

                parsed_headers = {}
                if pd.notna(headers_raw):
                    try:
                        parsed_headers = json.loads(str(headers_raw))
                    except Exception:
                        pass

                if user_cookie.strip():
                    parsed_headers["Cookie"] = user_cookie.strip()

                parsed_apis.append({
                    "name": f"{scenario_name}_{name}",
                    "method": str(method),
                    "base_url": str(base_url) if pd.notna(base_url) else "${BASE_URL}",
                    "path": str(endpoint) if pd.notna(endpoint) else "/",
                    "headers": parsed_headers,
                    "body": body if pd.notna(body) else None
                })

    elif source_type == "Swagger / OpenAPI JSON":
        swagger_file = st.file_uploader("Upload OpenAPI/Swagger JSON", type=["json"], key="tab1_swagger")
        if swagger_file:
            swagger_data = json.load(swagger_file)
            host = swagger_data.get("host", "${BASE_URL}")
            paths = swagger_data.get("paths", {})
            for path, methods in paths.items():
                for method, details in methods.items():
                    headers = {"Content-Type": "application/json", "Accept": "application/json"}
                    if user_cookie.strip():
                        headers["Cookie"] = user_cookie.strip()
                    parsed_apis.append({
                        "name": f"{scenario_name}_{method.upper()}_{path.strip('/').replace('/', '_')}",
                        "method": method.upper(),
                        "base_url": host,
                        "path": path,
                        "headers": headers
                    })

    if st.button("Generate Clean JMX Script", key="btn_gen_tab1"):
        if parsed_apis:
            jmx_output = create_standard_jmx(parsed_apis, test_plan_name=f"{scenario_name} Test Plan",
                                             jar_paths=jar_file_paths)
            st.success(f"Successfully generated JMX script for {len(parsed_apis)} unique endpoints!")
            st.download_button("💾 Download Clean .jmx File", data=jmx_output,
                               file_name=f"{scenario_name}_test_plan.jmx", mime="text/xml")
        else:
            st.error("Please upload a valid file or provide API text input.")

# ------------------------------------------
# TAB 2: RECOMMENDATION ENGINE
# ------------------------------------------
with tab2:
    st.header("Filter Enterprise API Lists to Core Scenarios")
    excel_recom = st.file_uploader("Upload API Collection (Excel/CSV/HAR)", type=["xlsx", "csv", "har", "json"],
                                   key="recom")

    if excel_recom:
        if excel_recom.name.endswith(".har") or excel_recom.name.endswith(".json"):
            har_json = json.load(excel_recom)
            parsed_apis_raw = parse_har_file(har_json)
            df_all = pd.DataFrame(
                [{"Path": a["path"], "Method": a["method"], "Domain": a["base_url"], "Name": a["name"]} for a in
                 parsed_apis_raw])
        else:
            df_all = pd.read_csv(excel_recom) if excel_recom.name.endswith(".csv") else pd.read_excel(excel_recom)

        st.write(f"Total APIs found: **{len(df_all)}**")

        col1, col2 = st.columns(2)
        with col1:
            exclude_static = st.checkbox("Exclude static assets (.png, .css, .js)", value=True)
            filter_health = st.checkbox("Exclude health/monitoring endpoints", value=True)
        with col2:
            keywords = st.text_input("Include APIs matching scenario keywords:",
                                     "restaurant, order, active, filter-info, map-box")

        if st.button("Filter Core Scenarios"):
            kw_list = [k.strip().lower() for k in keywords.split(",")]
            filtered_rows = []

            for _, row in df_all.iterrows():
                path = str(row.get("Path") or row.get("endPoint") or "").lower()

                if exclude_static and any(
                        path.endswith(ext) for ext in [".css", ".js", ".png", ".jpg", ".svg", ".ico"]):
                    continue
                if filter_health and any(h in path for h in ["health", "metrics", "heartbeat", "favicon"]):
                    continue

                if any(kw in path for kw in kw_list):
                    filtered_rows.append(row)

            res_df = pd.DataFrame(filtered_rows)
            st.success(f"Reduced down to **{len(res_df)}** mandatory scenario APIs!")
            st.dataframe(res_df)

# ------------------------------------------
# TAB 3: CLEAN WEB RECORDER
# ------------------------------------------
with tab3:
    st.header("Noise-Free Traffic Recorder")
    target_url = st.text_input("Target Web Application URL:", "https://delivery-zone.foodtruck-qa.com")

    if st.button("Start Capture Session"):
        st.warning("Proxy listening... (Simulated Capture Active)")
        captured = [
            {"name": f"{scenario_name}_GET_map_box_access_token", "method": "GET",
             "base_url": "delivery-zone.foodtruck-qa.com", "path": "/ajax/map-box-access-token",
             "headers": {"Content-Type": "application/json", "Accept": "application/json"}},
            {"name": f"{scenario_name}_PUT_delivery_zone_geometry", "method": "PUT",
             "base_url": "delivery-zone.foodtruck-qa.com", "path": "/ajax/delivery-zone-geometry",
             "headers": {"Content-Type": "application/json", "Accept": "application/json"},
             "body": '{"geometry":{"type":"Polygon","coordinates":[]}}'}
        ]
        st.json(captured)
        jmx_clean = create_standard_jmx(captured, f"{scenario_name} Recorded Session", jar_paths=jar_file_paths)
        st.download_button("💾 Download Clean Recorded .jmx", data=jmx_clean, file_name=f"{scenario_name}_recorded.jmx",
                           mime="text/xml")

# ------------------------------------------
# TAB 4: SCRIPT EDITOR & TUNER
# ------------------------------------------
with tab4:
    st.header("Modify Generated JMX Script")
    uploaded_jmx = st.file_uploader("Upload JMX File to Tune", type=["jmx"], key="tab4_jmx")

    if uploaded_jmx:
        jmx_text = uploaded_jmx.read().decode("utf-8")

        col_a, col_b = st.columns(2)
        with col_a:
            new_threads = st.number_input("Target User Threads", min_value=1, max_value=10000, value=50)
            new_rampup = st.number_input("Ramp-up Time (seconds)", min_value=1, max_value=3600, value=10)
        with col_b:
            override_domain = st.text_input("Override Target Server Domain/IP:",
                                            placeholder="delivery-zone.foodtruck-qa.com")

        if st.button("Apply Modifications"):
            modified_jmx = re.sub(r'(<stringProp name="ThreadGroup\.num_threads">)(\d+)(</stringProp>)',
                                  f'\\1{new_threads}\\3', jmx_text)
            modified_jmx = re.sub(r'(<stringProp name="ThreadGroup\.ramp_time">)(\d+)(</stringProp>)',
                                  f'\\1{new_rampup}\\3', modified_jmx)

            if override_domain:
                modified_jmx = re.sub(r'(<stringProp name="HTTPSampler\.domain">)(.*?)(</stringProp>)',
                                      f'\\1{override_domain}\\3', modified_jmx)

            st.success("JMX updated successfully!")
            st.download_button("💾 Download Modified JMX", data=modified_jmx, file_name="modified_test_plan.jmx",
                               mime="text/xml")