import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
    vus: 10,
    duration: '1m',
};

const BASE_URL = 'https://agentflow-dev.tigeranalyticstest.in/aiapi';
const AUTH_URL = 'https://login.microsoftonline.com/e714ef31-faab-41d2-9f1e-e6df4af16ab8/oauth2/v2.0/token';
let bearerToken = '';

export function setup() {
    const authPayload = 'client_id=4722cb40-93b0-4c58-83fa-245cb7651152&scope=api://eksagentflow.tigermlcore.com/4722cb40-93b0-4c58-83fa-245cb7651152/access_as_user openid profile User.Read offline_access&grant_type=refresh_token&client_info=1&x-client-SKU=msal.js.browser&x-client-VER=4.30.0&refresh_token=1.AVYAMe8U56v60kGfHubfSvFquEDLIkewk1hMg_okXLdlEVIAAPVWAA.BQABAwEAAAADAOz_BQD0_0V2b1N0c0FydGlmYWN0cwIAAAAAAFJS6Mh6OXSPzNaxBCJWf6UzT-T7vGLrNQtSICKjfu7GgIY_OUphGB3A6bhv5XwgfADiuOmd3xM0Ray7ceEbZHTvMzZDwvSRjW9GZqJNdUUvZMWeMnCeZ88bDm7vwYKu7aQ8HwiBYmAZKG8eSTROBEOn44yT4D9Vjj_zpFQ9oKQY6PiwYq9ppLNt072X_8_ZjKHwMaX-rxvYNdBiz9wC_UcXFSGOeow1gTbl29ODIYH3HmIwzReEvY58cckNX7ujLEmcr3FmlZmCHVfDIgHLxlMGqhW5zCp9sFbMIn2dSIuBfDjYEW7lh_54VDD-UMsg21f9L7sCaY1LIEcLzyWH0izacx-rIjxffjXChom131AO_BGaJs_XU1-5WJINAb5fk3YJzfR7KgYiESKM4bKHr2iBEaANfZqZb0Q9h6JygS65vMzMZbYzasMr-pSNqAjdMi51aEnrmfwwwbHpj8DWzh4P1XnoDQ2HLN2aDP769i-Y1qCrIqWDj8seiHz-ZZIpfYoJ3rHr5oBPf8MsP7HsejUrgKk7-IOMWCRBqwkn986GveBSVyWQ4TuSjb9Cyqzx4Wf_wkCa3yKnrHQaM6L4Cy57uJItwHGUTdh8eJmTcuZ7lyZV0xifO_j4Xf4gIaTTftvtap6qePZ0RmxMyb7zCkTEP4fp1z2--JhrjPxLroPgwncySSRuyFYyjMKHzTem-OVsd_nKJpsVguJM80HrTTAePKEwklsf1PKP9fXbqSa4ajKmEcU-BA2XeVSwMGRZ-cAYIrpjH1b7Fd7V2yO-yx3BGC-DzoijM4EeM_QeCr3aiMM-hr2KHC5xhDFlbFj7pj4qYx70R4Fh2E6EQMi1WALrP1GoqrrAlYwLG-RuXrWgko-xKTZ_YQqlKGLgRVqrm6HYxfxCJd5bZxgtfRsrObhwRDXs9tzcICLs6I2qTr-5ZWZGDvAV08O_8K26ar05netfqugOw6AeExCpWbOFS0NcYX-312JBmgAda0GbOisrzxGx1h-6q4wmE5Z0vtSXMiysg8ug-1fZjj1x-OhjWwEVw8kMqjzmgAqUAUVfqLy_ADeI3tJDyUEml92dxXEx0GPyzPo1Y7i0aDq6JpeXXW6RItr8N4GotyaPU9wzd87Lzz158_tJwWBJRnZIDsS-REQwvY3Hx0FLi32kglMdppu7SPqGckh9mkDMx-0atf2KdfJCjuFP9qJGrjcZ8vMx2Z2hLx5I3f9Xu4_RRSN4_kH24mvApBitcK_HxJPeGIASn5nXzgAbZORtJ4pVkfgDX6xsM_KwmwORkMX7qF4PdSm3Y2txheCfvBaAQbxN_4pt2Tn6Senc-qHK_CaZvNAlhEytG8CU3Ls5EF8V3nS94dmtM0higViwpxfNJ-HYNLsc1DiYWhJfzCw0e-hoN3efer8fxXg';
    const headers = {
        'Content-Type': 'application/x-www-form-urlencoded',
        'Origin': 'https://agentflow-dev.tigeranalyticstest.in',
        'Referer': 'https://agentflow-dev.tigeranalyticstest.in/',
    };

    const response = http.post(AUTH_URL, authPayload, { headers });
    check(response, { 'auth success': (r) => r.status === 200 });

    const jsonResponse = JSON.parse(response.body);
    bearerToken = jsonResponse.access_token;

    return { bearerToken };
}

export default function (data) {
    const headers = {
        Authorization: `Bearer ${data.bearerToken}`,
        'Content-Type': 'application/json',
    };

    // TC001_Prompts_Create
    let payload = JSON.stringify({
        prompt_name: `prompt_${Math.random().toString(36).substring(7)}`,
        prompt_text: 'This is a test prompt Generated by JMeter',
        project_id: '',
        description: 'jnk',
        tags: [],
    });
    let res = http.post(`${BASE_URL}/prompts/create`, payload, { headers });
    check(res, { 'TC001 status 200': (r) => r.status === 200 });

    // TC002_Prompts_Clone
    const promptId = JSON.parse(res.body).data[0].prompt_id;
    payload = JSON.stringify({
        source_prompt_id: promptId,
        prompt_name: `cloned_${Math.random().toString(36).substring(2, 4)}`,
        version: '1.0',
    });
    res = http.post(`${BASE_URL}/prompts/clone`, payload, { headers });
    check(res, { 'TC002 status 200': (r) => r.status === 200 });

    // TC003_Prompts_List
    const queryParams = {
        page_size: 20,
        page: 1,
        marker_id: '',
        page_mode: 'string',
        mode: 'paginated',
        prompt_category: 'string',
        agent_id: 'string',
        api_mode: 'list',
        bookmark: 'False',
        search: 'string',
        tags: 'string',
        version: 'string',
        prompt_id: 'string',
        latest_only: true,
        policy: 'string',
    };
    res = http.get(`${BASE_URL}/prompts/list`, { headers, params: queryParams });
    check(res, { 'TC003 status 200': (r) => r.status === 200 });

    // TC004_Prompts_Update
    payload = JSON.stringify({
        prompt_id: 'sample_prompt_id',
        prompt_name: 'sample_prompt_name',
        prompt_text: 'sample_prompt_text',
        description: 'sample_description',
        tags: [],
    });
    res = http.put(`${BASE_URL}/prompts/update`, payload, { headers });
    check(res, { 'TC004 status 200': (r) => r.status === 200 });

    // TC005_Prompts_Remove_Cloned
    payload = JSON.stringify({ prompt_id: promptId });
    res = http.put(`${BASE_URL}/prompts/remove`, payload, { headers });
    check(res, { 'TC005 status 200': (r) => r.status === 200 });

    // TC006_Prompts_Refine
    payload = JSON.stringify({
        prompt_text: 'prompts are used to generate response quickly',
        refine_instruction: 'make it shorter',
    });
    res = http.post(`${BASE_URL}/prompts/refine`, payload, { headers });
    check(res, { 'TC006 status 200': (r) => r.status === 200 });

    // TC007_Prompts_Uniqueness
    res = http.get(`${BASE_URL}/prompts/uniqueness?name=sample_name`, { headers });
    check(res, { 'TC007 status 200': (r) => r.status === 200 });

    // TC008_Get_Unique_Prompts
    res = http.get(`${BASE_URL}/prompts/tags?prompt_library=false`, { headers });
    check(res, { 'TC008 status 200': (r) => r.status === 200 });

    // TC009_Prompt_Tags
    res = http.get(`${BASE_URL}/prompts/search?query=sample_query`, { headers });
    check(res, { 'TC009 status 200': (r) => r.status === 200 });

    // TC010_Savedraft
    payload = JSON.stringify({
        agent_architecture: {
            nodes: [
                {
                    id: 'b1a78bfb-c054-4d47-8909-74b95e889728',
                    type: 'core_node',
                    position: { x: -266.28417309847737, y: 423.41652471368974 },
                    data: {
                        color: '#2BA7E0',
                        name: 'Start',
                        node_type: 'chat_input',
                        node_family: 'system',
                        disableInput: false,
                        disableOutput: false,
                        form: { history_context_length: 5 },
                        input_keys: [],
                    },
                    deletable: false,
                },
                {
                    id: 'd7b91222-fd51-4c4a-ae46-7ad9708e48a6',
                    type: 'core_node',
                    position: { x: 1509.6249178106134, y: 438.9922822894472 },
                    data: {
                        color: '#4070F5',
                        name: 'End',
                        node_type: 'chat_output',
                        node_family: 'system',
                        disableInput: false,
                        disableOutput: false,
                        form: {},
                    },
                    deletable: false,
                },
            ],
            edges: [],
        },
        canvas_version: '1.0.1',
        name: `agent_${Math.random().toString(36).substring(7)}`,
        description: '',
        source: 'Manual',
        agent_framework: 'langgraph',
    });
    res = http.post(`${BASE_URL}/agents/save_draft`, payload, { headers });
    check(res, { 'TC010 status 200': (r) => r.status === 200 });

    sleep(1);
}