# --- Azure OpenAI Configuration Keys ---
AZURE_OPENAI_API_KEY = "4fed2bedb59744a99b0424622f6d9d1b"
AZURE_OPENAI_ENDPOINT = "https://qepracticekey.openai.azure.com/"

# --- Azure Monitor Service Principal Credentials ---
AZURE_TENANT_ID = "e714ef31-faab-41d2-9f1e-e6df4af16ab8"
AZURE_CLIENT_ID = "9fd4c111-f1cf-4e2a-a6bd-4fb579a57d6d"
AZURE_CLIENT_SECRET = "QpA8Q~IWnTe5TN6Z9vCV4yiDO-R.bf5a1D.Iob5V"

# 📊 LOCAL INFLUXDB 1.8 TELEMETRY CONFIGURATION
INFLUX_URL = "http://localhost:8086"
INFLUX_DB = "jmeter"

INFLUX_USER = ""
INFLUX_PASSWORD = ""